name: 2P Daily

on:

  schedule:

    - cron: '6 8 * * *'
    - cron: '38 9 * * *'
    - cron: '37 10 * * *'

  workflow_dispatch:

jobs:

  run:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # ====================================
      # CHECK GITHUB TIME
      # ====================================

      - name: Show Scheduler Time
        run: |
          echo "==========================="
          echo "UTC TIME"
          date
          echo "==========================="
          echo "VIETNAM TIME"
          TZ=Asia/Ho_Chi_Minh date
          echo "==========================="

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run lottery report
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
