name: 2P Daily

on:
  workflow_dispatch:

jobs:

  run:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # ====================================
      # CHECK TIME
      # ====================================

      - name: Show Runtime Time
        run: |
          echo "==========================="
          echo "EVENT"
          echo "${{ github.event_name }}"
          echo "==========================="
          echo "UTC TIME"
          date
          echo "==========================="
          echo "VIETNAM TIME"
          TZ=Asia/Ho_Chi_Minh date
          echo "==========================="

      # ====================================
      # INSTALL
      # ====================================

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ====================================
      # RUN
      # ====================================

      - name: Run lottery report
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
